/*
 * Copyright (C) 2019 ashary
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package app;
import java.sql.*;
import java.util.*;
import java.util.logging.*;
import lib.Koneksi;
import entity.KategoriEntity;
import javax.swing.table.TableModel;
import model.KategoriTableModel;

/**
 *
 * @author ashary
 */
public class Kategori extends javax.swing.JFrame {
    private final Connection db;
    private String id;

    /**
     * Creates new form User
     */
    public Kategori() {
        initComponents();
        db = (new Koneksi()).getCon();
        
        changeInputState(false);
        changeBtnState(false, "");
        showData();
        
    }
    
    private void showData() {
        List<KategoriEntity> kat = new ArrayList<>();
        try (PreparedStatement ps = db.prepareStatement("SELECT * FROM `kategori`")) {
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                KategoriEntity kategori = new KategoriEntity();
                kategori.setKode(rs.getString("kd_kategori"));
                kategori.setNama(rs.getString("nm_kategori"));
                kat.add(kategori);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Kategori.class.getName()).log(Level.SEVERE, null, ex);
        }
        KategoriTableModel tabelKategori = new KategoriTableModel(kat);
        kategoriTbl.setModel(tabelKategori);
    }

    private void reset() {
        kodeKategoriTxt.setText(null);
        namaKategoriTxt.setText(null);
        kategoriTbl.clearSelection();
    }

    private void changeInputState(boolean b) {
        kodeKategoriTxt.setEnabled(b);
        namaKategoriTxt.setEnabled(b);
    }
    
    private void changeBtnState(boolean b, String btn) {
        switch (btn) {
            case "new":
                newBtn.setEnabled(!b);
                batalBtn.setEnabled(b);
                
                hapusBtn.setEnabled(!b);
                editBtn.setEnabled(!b);
                simpanBtn.setEnabled(b);
            break;
            case "edit/delete":
                newBtn.setEnabled(!b);
                batalBtn.setEnabled(b);
                
                hapusBtn.setEnabled(b);
                editBtn.setEnabled(b);
                simpanBtn.setEnabled(!b);
            break;
            case "simpan": 
            default:
                newBtn.setEnabled(!b);
                batalBtn.setEnabled(b);
                
                hapusBtn.setEnabled(b);
                editBtn.setEnabled(b);
                simpanBtn.setEnabled(b);
            break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kodeKategoriTxt = new javax.swing.JTextField();
        namaKategoriTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        kategoriTbl = new javax.swing.JTable();
        batalBtn = new javax.swing.JButton();
        simpanBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        newBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kategori");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kategori");

        jLabel2.setText("Kode Kategori");

        jLabel3.setText("Nama Kategori");

        kategoriTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        kategoriTbl.setAutoscrolls(false);
        kategoriTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        kategoriTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kategoriTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(kategoriTbl);

        batalBtn.setText("Batal");
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });

        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        newBtn.setText("New");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodeKategoriTxt)
                    .addComponent(namaKategoriTxt))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(batalBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapusBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editBtn)
                        .addGap(75, 75, 75)
                        .addComponent(simpanBtn)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kodeKategoriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaKategoriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batalBtn)
                    .addComponent(simpanBtn)
                    .addComponent(editBtn)
                    .addComponent(hapusBtn)
                    .addComponent(newBtn))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        try (PreparedStatement ps = db.prepareStatement("INSERT INTO `kategori` VALUES (?,?)")) {
            ps.setString(1, kodeKategoriTxt.getText());
            ps.setString(2, namaKategoriTxt.getText());
            ps.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Kategori.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
        reset();
        changeInputState(false);
        changeBtnState(false, "simpan");
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        changeInputState(true);
        changeBtnState(true, "new");
    }//GEN-LAST:event_newBtnActionPerformed

    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        reset();
        changeInputState(false);
        changeBtnState(false, "batal");
    }//GEN-LAST:event_batalBtnActionPerformed

    private void kategoriTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kategoriTblMouseClicked
        TableModel table = kategoriTbl.getModel();
        int row = kategoriTbl.getSelectedRow();
        id = table.getValueAt(row, 0).toString();

        try (PreparedStatement ps = db.prepareStatement("SELECT * FROM `kategori` WHERE `kd_kategori` = ?")) {
            ps.setString(1, id);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                kodeKategoriTxt.setText(rs.getString("kd_kategori"));
                namaKategoriTxt.setText(rs.getString("nm_kategori"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Kategori.class.getName()).log(Level.SEVERE, null, ex);
        }
        changeInputState(true);
        changeBtnState(true, "edit/delete");
        kodeKategoriTxt.setEnabled(false);
    }//GEN-LAST:event_kategoriTblMouseClicked

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        String kd_kategori = kodeKategoriTxt.getText();
        try (Statement stmt = db.createStatement()) {
            stmt.execute("DELETE FROM `kategori` WHERE `kd_kategori` = '"+kd_kategori+"'");
        } catch (SQLException ex) {
            Logger.getLogger(Kategori.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
        reset();
        changeInputState(false);
        changeBtnState(false, "simpan");
        kategoriTbl.clearSelection();
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        String kd_kategori = kodeKategoriTxt.getText();
        String nm_kategori = namaKategoriTxt.getText();
        try (Statement stmt = db.createStatement()) {
            stmt.execute("UPDATE `kategori` SET `nm_kategori` = '"+nm_kategori+"' WHERE `kd_kategori` = '"+kd_kategori+"'");
        } catch (SQLException ex) {
            Logger.getLogger(Kategori.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
        reset();
        changeInputState(false);
        changeBtnState(false, "simpan");
        kategoriTbl.clearSelection();
    }//GEN-LAST:event_editBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Kategori().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable kategoriTbl;
    private javax.swing.JTextField kodeKategoriTxt;
    private javax.swing.JTextField namaKategoriTxt;
    private javax.swing.JButton newBtn;
    private javax.swing.JButton simpanBtn;
    // End of variables declaration//GEN-END:variables

}
