/*
 * Copyright (C) 2019 ashary
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lib.Koneksi;

/**
 *
 * @author ashary
 */
public class Peminjaman extends javax.swing.JFrame {
    private final Connection db;
    private int row;

    /**
     * Creates new form Peminjaman
     */
    public Peminjaman() {
        initComponents();
        
        db = (new Koneksi()).getCon();
        
        reset(false);
        hapusBtn.setEnabled(false);
        
        String data[][] = {};
        String col[] = {"Kode Buku", "Judul", "Jumlah"};
        DefaultTableModel model = new DefaultTableModel(data, col);
        bukuTbl.setModel(model);
    }
    
    private String getNoPinjam() {
        String now = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        
        try (PreparedStatement stat = db.prepareStatement("SELECT `no_pinjam` FROM `peminjaman` ORDER BY `id` DESC LIMIT 1")) {
            ResultSet rs = stat.executeQuery();
            if (rs.next()) {
                int no_pinjam;
                no_pinjam = Integer.parseInt(rs.getString("no_pinjam").split("_")[0]) + 1;
                return String.format("%03d_%s", no_pinjam, now);
            } else {
                return "001_" + now;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Peminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }
    
    private void reset(Boolean item) {
        noPinjamTxt.setText(getNoPinjam());
        tglPinjamTxt.setDate(new Date());
        siswaTxt.removeAllItems();
        userTxt.removeAllItems();
        tglKembaliTxt.setDate(null);
        
        if (item) {
            bukuTxt.removeAllItems();
            judulTxt.setText(null);
            jumlahTxt.setText(null);
            bukuTbl.removeAll();
        }
    }
    
    private void searchUser(String cari) {
        try (PreparedStatement stat = db.prepareStatement("SELECT * FROM `user` WHERE `nm_user` LIKE ?")) {
            stat.setString(1, "%"+ cari +"%");
            ResultSet rs = stat.executeQuery();
            userTxt.removeAllItems();
            while (rs.next()) {
                userTxt.addItem(rs.getString("kd_user") + " - " + rs.getString("nm_user"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Peminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void searchSiswa(String cari) {
        try (PreparedStatement stat = db.prepareStatement("SELECT * FROM `siswa` WHERE `nm_siswa` LIKE ?")) {
            stat.setString(1, "%"+ cari +"%");
            ResultSet rs = stat.executeQuery();
            siswaTxt.removeAllItems();
            while (rs.next()) {
                siswaTxt.addItem(rs.getString("kd_siswa") + " - " + rs.getString("nm_siswa"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Peminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void searchBuku(String cari) {
        try (PreparedStatement stat = db.prepareStatement("SELECT * FROM `buku` WHERE `judul` LIKE ?")) {
            stat.setString(1, "%"+ cari +"%");
            ResultSet rs = stat.executeQuery();
            bukuTxt.removeAllItems();
            while (rs.next()) {
                String judul = rs.getString("judul");
                judulTxt.setText(judul);
                bukuTxt.addItem(rs.getString("kd_buku") + " - " + judul);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Peminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        noPinjamTxt = new javax.swing.JTextField();
        cariSiswaTxt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tglPinjamTxt = new com.toedter.calendar.JDateChooser();
        tglKembaliTxt = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cariBukuTxt = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        judulTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tambahkanBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bukuTbl = new javax.swing.JTable();
        simpanBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        cariUserBtn = new javax.swing.JButton();
        siswaTxt = new javax.swing.JComboBox<>();
        userTxt = new javax.swing.JComboBox<>();
        bukuTxt = new javax.swing.JComboBox<>();
        jumlahTxt = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Peminjaman");
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Peminjaman");

        jLabel2.setText("Nomor Pinjam");

        jLabel3.setText("Tanggal Pinjam");

        jLabel4.setText("Siswa");

        cariSiswaTxt.setText("Cari");
        cariSiswaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariSiswaTxtActionPerformed(evt);
            }
        });

        jLabel5.setText("User");

        jLabel6.setText("Tanggal Kembali");

        jLabel7.setText("Buku");

        cariBukuTxt.setText("Cari");
        cariBukuTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBukuTxtActionPerformed(evt);
            }
        });

        jLabel8.setText("Judul");

        jLabel9.setText("Jumlah");

        tambahkanBtn.setText("Tambahkan");
        tambahkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkanBtnActionPerformed(evt);
            }
        });

        bukuTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bukuTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        bukuTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bukuTbl);

        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        cariUserBtn.setText("Cari");
        cariUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(siswaTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cariSiswaTxt)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(judulTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tglPinjamTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(noPinjamTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(bukuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cariBukuTxt)
                            .addGap(275, 275, 275)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tglKembaliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cariUserBtn)
                                        .addGap(23, 23, 23))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(41, 41, 41)
                                .addComponent(jumlahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tambahkanBtn)))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hapusBtn)
                            .addComponent(simpanBtn))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cariUserBtn)
                        .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(noPinjamTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6))
                            .addComponent(tglPinjamTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cariSiswaTxt)
                            .addComponent(siswaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(tglKembaliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cariBukuTxt)
                    .addComponent(jLabel8)
                    .addComponent(judulTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tambahkanBtn)
                    .addComponent(bukuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hapusBtn)
                        .addGap(18, 18, 18)
                        .addComponent(simpanBtn)))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tambahkanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkanBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) bukuTbl.getModel();
        String id = bukuTxt.getSelectedItem().toString().split(" - ")[0];
        String title = judulTxt.getText();
        String total = jumlahTxt.getText();
        
        model.addRow(new String[]{id, title, total});
        bukuTxt.removeAllItems();
        judulTxt.setText(null);
        jumlahTxt.setText(null);
    }//GEN-LAST:event_tambahkanBtnActionPerformed

    private void cariSiswaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariSiswaTxtActionPerformed
        String cari = JOptionPane.showInputDialog(this, "Siswa :");
        searchSiswa(cari);
    }//GEN-LAST:event_cariSiswaTxtActionPerformed

    private void cariUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariUserBtnActionPerformed
        String cari = JOptionPane.showInputDialog(this, "User :");
        searchUser(cari);
    }//GEN-LAST:event_cariUserBtnActionPerformed

    private void cariBukuTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBukuTxtActionPerformed
        String cari = JOptionPane.showInputDialog(this, "Buku :");
        searchBuku(cari);
    }//GEN-LAST:event_cariBukuTxtActionPerformed

    private void bukuTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuTblMouseClicked
        // TODO add your handling code here:
        TableModel table = bukuTbl.getModel();
        row = bukuTbl.getSelectedRow();
        hapusBtn.setEnabled(true);
    }//GEN-LAST:event_bukuTblMouseClicked

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        // TODO add your handling code here:
        ((DefaultTableModel)bukuTbl.getModel()).removeRow(row);
        bukuTbl.clearSelection();
        hapusBtn.setEnabled(false);
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        try (PreparedStatement ps = db.prepareStatement("INSERT INTO `peminjaman` (`no_pinjam`, `tgl_pinjam`, `kd_siswa`, `keterangan`, `tgl_kembali`, `status`, `kd_user`) VALUES (?,?,?,?,?,?,?)")) {
            java.sql.Date tglKembali = new java.sql.Date(tglKembaliTxt.getDate().getTime());
            java.sql.Date tglPinjam = new java.sql.Date(tglPinjamTxt.getDate().getTime());

            ps.setString(1, noPinjamTxt.getText());
            ps.setString(2, tglPinjam.toString());
            ps.setString(3, siswaTxt.getSelectedItem().toString().split(" - ")[0]);
            ps.setString(4, "");
            ps.setString(5, tglKembali.toString());
            ps.setString(6, "");
            ps.setString(7, userTxt.getSelectedItem().toString().split(" - ")[0]);
            ps.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                TableModel table = bukuTbl.getModel();
        try (PreparedStatement ps = db.prepareStatement("INSERT INTO `peminjaman_item` VALUES (?,?,?)")) {
            for (int i = 0; i < table.getRowCount(); i++) {
                ps.setString(1, noPinjamTxt.getText());
                ps.setString(2, table.getValueAt(i, 0).toString());
                ps.setString(3, table.getValueAt(i, 2).toString());
            }
            ps.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
        }
        reset(true);
    }//GEN-LAST:event_simpanBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bukuTbl;
    private javax.swing.JComboBox<String> bukuTxt;
    private javax.swing.JButton cariBukuTxt;
    private javax.swing.JButton cariSiswaTxt;
    private javax.swing.JButton cariUserBtn;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judulTxt;
    private javax.swing.JFormattedTextField jumlahTxt;
    private javax.swing.JTextField noPinjamTxt;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JComboBox<String> siswaTxt;
    private javax.swing.JButton tambahkanBtn;
    private com.toedter.calendar.JDateChooser tglKembaliTxt;
    private com.toedter.calendar.JDateChooser tglPinjamTxt;
    private javax.swing.JComboBox<String> userTxt;
    // End of variables declaration//GEN-END:variables
}
