/*
 * Copyright (C) 2019 ashary
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package app;

import java.sql.*;
import java.util.*;
import java.util.logging.*;
import lib.Koneksi;
import entity.PengadaanEntity;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.PengadaanTableModel;

/**
 *
 * @author ashary
 */
public class Pengadaan extends javax.swing.JFrame {
    private final Connection db;

    /**
     * Creates new form Pengadaan
     */
    public Pengadaan() {
        initComponents();
        db = (new Koneksi()).getCon();
        
        changeInputState(false);
        changeBtnState(false, "");
        showData();
    }
    
    private void showData() {
        List<PengadaanEntity> kat = new ArrayList<>();
        try (PreparedStatement ps = db.prepareStatement("SELECT * FROM `pengadaan`")) {
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                PengadaanEntity pengadaan = new PengadaanEntity();
                pengadaan.setNoPengadaan(rs.getString("no_pengadaan"));
                pengadaan.setTglPengadaan(rs.getString("tgl_pengadaan"));
                pengadaan.setKdBuku(rs.getString("kd_buku"));
                pengadaan.setAsalBuku(rs.getString("asal_buku"));
                pengadaan.setJumlah(rs.getString("jumlah"));
                pengadaan.setKeterangan(rs.getString("keterangan"));
                kat.add(pengadaan);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pengadaan.class.getName()).log(Level.SEVERE, null, ex);
        }
        PengadaanTableModel tabelPengadaan = new PengadaanTableModel(kat);
        pengadaanTbl.setModel(tabelPengadaan);
    }
    
    private void reset() {
        noPengadaanTxt.setText(null);
        tglPengadaanTxt.setDate(null);
        kdBukuTxt.setText(null);
        jumlahTxt.setText(null);
        keteranganTxt.setText(null);
        pengadaanTbl.clearSelection();
    }

    private void changeInputState(boolean b) {
        noPengadaanTxt.setEnabled(b);
        tglPengadaanTxt.setEnabled(b);
        kdBukuTxt.setEnabled(b);
        jumlahTxt.setEnabled(b);
        keteranganTxt.setEnabled(b);
    }
    
    private void changeBtnState(boolean b, String btn) {
        switch (btn) {
            case "new":
                newBtn.setEnabled(!b);
                batalBtn.setEnabled(b);
                
                hapusBtn.setEnabled(!b);
                editBtn.setEnabled(!b);
                simpanBtn.setEnabled(b);
            break;
            case "edit/delete":
                newBtn.setEnabled(!b);
                batalBtn.setEnabled(b);
                
                hapusBtn.setEnabled(b);
                editBtn.setEnabled(b);
                simpanBtn.setEnabled(!b);
            break;
            case "simpan": 
            default:
                newBtn.setEnabled(!b);
                batalBtn.setEnabled(b);
                
                hapusBtn.setEnabled(b);
                editBtn.setEnabled(b);
                simpanBtn.setEnabled(b);
            break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        noPengadaanTxt = new javax.swing.JTextField();
        kdBukuTxt = new javax.swing.JTextField();
        tglPengadaanTxt = new com.toedter.calendar.JDateChooser();
        jumlahTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        keteranganTxt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        pengadaanTbl = new javax.swing.JTable();
        batalBtn = new javax.swing.JButton();
        simpanBtn = new javax.swing.JButton();
        newBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pengadaan");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pengadaan");

        jLabel2.setText("No Pengadaan");

        jLabel3.setText("Tanggal Pengadaan");

        jLabel4.setText("Buku");

        jLabel5.setText("Jumlah");

        jLabel6.setText("Keterangan");

        keteranganTxt.setColumns(20);
        keteranganTxt.setRows(5);
        jScrollPane1.setViewportView(keteranganTxt);

        pengadaanTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pengadaanTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengadaanTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pengadaanTbl);

        batalBtn.setText("Batal");
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });

        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        newBtn.setText("New");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(batalBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(newBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editBtn)
                        .addGap(18, 18, 18)
                        .addComponent(hapusBtn)
                        .addGap(87, 87, 87)
                        .addComponent(simpanBtn))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(noPengadaanTxt)
                            .addComponent(kdBukuTxt)
                            .addComponent(tglPengadaanTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jumlahTxt)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(noPengadaanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tglPengadaanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(kdBukuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jumlahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batalBtn)
                    .addComponent(simpanBtn)
                    .addComponent(newBtn)
                    .addComponent(editBtn)
                    .addComponent(hapusBtn))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        // TODO add your handling code here:
        reset();
        changeInputState(false);
        changeBtnState(false, "batal");
    }//GEN-LAST:event_batalBtnActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        // TODO add your handling code here:
        changeInputState(true);
        changeBtnState(true, "new");
    }//GEN-LAST:event_newBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        String noPengadaan = noPengadaanTxt.getText();
        String tglPengadaan = new java.sql.Date(tglPengadaanTxt.getDate().getTime()).toString();
        String kdBuku = kdBukuTxt.getText();
        String jumlah = jumlahTxt.getText();
        String keterangan = keteranganTxt.getText();
        try (Statement stmt = db.createStatement()) {
            stmt.execute("UPDATE `pengadaan` SET "
            + "`tglPengadaan` = '"+tglPengadaan+"', `kd_buku` = '"+kdBuku+"', `jumlah` = '"+jumlah+"', `keterangan` = '"+keterangan+"' " 
            + "WHERE `no_pengadaan` = '"+noPengadaan+"'");
        } catch (SQLException ex) {
            Logger.getLogger(Pengadaan.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
        reset();
        changeInputState(false);
        changeBtnState(false, "simpan");
        pengadaanTbl.clearSelection();
    }//GEN-LAST:event_editBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        // TODO add your handling code here:
        String no_pengadaan = noPengadaanTxt.getText();
        try (Statement stmt = db.createStatement()) {
            stmt.execute("DELETE FROM `pengadaan` WHERE `no_pengadaan` = '"+no_pengadaan+"'");
        } catch (SQLException ex) {
            Logger.getLogger(Pengadaan.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
        reset();
        changeInputState(false);
        changeBtnState(false, "simpan");
        pengadaanTbl.clearSelection();
        
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        try (PreparedStatement ps = db.prepareStatement("INSERT INTO `pengadaan` VALUES (?,?,?,?,?,?)")) {
            ps.setString(1, noPengadaanTxt.getText());
            ps.setString(2, new java.sql.Date(tglPengadaanTxt.getDate().getTime()).toString());
            ps.setString(3, kdBukuTxt.getText());
            ps.setString(4, "");
            ps.setString(5, jumlahTxt.getText());
            ps.setString(6, keteranganTxt.getText());
            ps.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Pengadaan.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
        reset();
        changeInputState(false);
        changeBtnState(false, "simpan");
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void pengadaanTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengadaanTblMouseClicked
        // TODO add your handling code here:
        TableModel table = pengadaanTbl.getModel();
        int row = pengadaanTbl.getSelectedRow();
        String id = table.getValueAt(row, 0).toString();

        try (PreparedStatement ps = db.prepareStatement("SELECT * FROM `pengadaan` WHERE `no_pengadaan` = ?")) {
            ps.setString(1, id);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                noPengadaanTxt.setText(rs.getString("no_pengadaan"));
                tglPengadaanTxt.setDate(java.sql.Date.valueOf(rs.getString("tgl_pengadaan")));
                kdBukuTxt.setText(rs.getString("kd_buku"));
                jumlahTxt.setText(rs.getString("jumlah"));
                keteranganTxt.setText(rs.getString("keterangan"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pengadaan.class.getName()).log(Level.SEVERE, null, ex);
        }
        changeInputState(true);
        changeBtnState(true, "edit/delete");
        noPengadaanTxt.setEnabled(false);
    }//GEN-LAST:event_pengadaanTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengadaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlahTxt;
    private javax.swing.JTextField kdBukuTxt;
    private javax.swing.JTextArea keteranganTxt;
    private javax.swing.JButton newBtn;
    private javax.swing.JTextField noPengadaanTxt;
    private javax.swing.JTable pengadaanTbl;
    private javax.swing.JButton simpanBtn;
    private com.toedter.calendar.JDateChooser tglPengadaanTxt;
    // End of variables declaration//GEN-END:variables
}
