/*
 * Copyright (C) 2019 ashary
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package app;

import java.sql.*;
import java.util.*;
import java.util.logging.*;
import lib.Koneksi;
import entity.SiswaEntity;
import javax.swing.table.TableModel;
import model.SiswaTableModel;

/**
 *
 * @author ashary
 */
public class Siswa extends javax.swing.JFrame {
    private final Connection db;

    /**
     * Creates new form Siswa
     */
    public Siswa() {
        initComponents();
        db = (new Koneksi()).getCon();
        
        changeInputState(false);
        changeBtnState(false, "");
        showData();
    }
    
    private void showData() {
        List<SiswaEntity> kat = new ArrayList<>();
        try (PreparedStatement ps = db.prepareStatement("SELECT * FROM `siswa`")) {
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                SiswaEntity siswa = new SiswaEntity();
                siswa.setKode(rs.getString("kd_siswa"));
                siswa.setNama(rs.getString("nm_siswa"));
                siswa.setNisn(rs.getString("nisn"));
                siswa.setKelamin(rs.getString("kelamin"));
                siswa.setAgama(rs.getString("agama"));
                siswa.setTempatLahir(rs.getString("tempat_lahir"));
                siswa.setTanggalLahir(rs.getString("tanggal_lahir"));
                siswa.setAlamat(rs.getString("alamat"));
                siswa.setTelp(rs.getString("no_telepon"));
                kat.add(siswa);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Siswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        SiswaTableModel tabelSiswa = new SiswaTableModel(kat);
        siswaTbl.setModel(tabelSiswa);
    }
    
    private void reset() {
        kodeSiswaTxt.setText(null);
        namaSiswaTxt.setText(null);
        nisnSiswaTxt.setText(null);
        jkSiswaTxt.clearSelection();
        agamaSiswaTxt.setSelectedItem("Islam");
        telaSiswaTxt.setText(null);
        talaSiswaTxt.setCalendar(null);
        alamatSiswaTxt.setText(null);
        siswaTbl.clearSelection();
        notelpSiswaTxt.setText(null);
    }

    private void changeInputState(boolean b) {
        kodeSiswaTxt.setEnabled(b);
        namaSiswaTxt.setEnabled(b);
        nisnSiswaTxt.setEnabled(b);
        jkLakiRdo.setEnabled(b);
        jkPerRdo.setEnabled(b);
        agamaSiswaTxt.setEnabled(b);
        telaSiswaTxt.setEnabled(b);
        talaSiswaTxt.setEnabled(b);
        alamatSiswaTxt.setEnabled(b);
        notelpSiswaTxt.setEnabled(b);
    }
    
    private void changeBtnState(boolean b, String btn) {
        switch (btn) {
            case "new":
                newBtn.setEnabled(!b);
                batalBtn.setEnabled(b);
                
                hapusBtn.setEnabled(!b);
                editBtn.setEnabled(!b);
                simpanBtn.setEnabled(b);
            break;
            case "edit/delete":
                newBtn.setEnabled(!b);
                batalBtn.setEnabled(b);
                
                hapusBtn.setEnabled(b);
                editBtn.setEnabled(b);
                simpanBtn.setEnabled(!b);
            break;
            case "simpan": 
            default:
                newBtn.setEnabled(!b);
                batalBtn.setEnabled(b);
                
                hapusBtn.setEnabled(b);
                editBtn.setEnabled(b);
                simpanBtn.setEnabled(b);
            break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkSiswaTxt = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kodeSiswaTxt = new javax.swing.JTextField();
        namaSiswaTxt = new javax.swing.JTextField();
        jkLakiRdo = new javax.swing.JRadioButton();
        jkPerRdo = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        agamaSiswaTxt = new javax.swing.JComboBox<>();
        telaSiswaTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatSiswaTxt = new javax.swing.JTextArea();
        talaSiswaTxt = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        siswaTbl = new javax.swing.JTable();
        batalBtn = new javax.swing.JButton();
        simpanBtn = new javax.swing.JButton();
        newBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        notelpSiswaTxt = new javax.swing.JFormattedTextField();
        nisnSiswaTxt = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Siswa");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Siswa");

        jLabel2.setText("Kode Siswa");

        jLabel3.setText("Nama Siswa");

        jLabel4.setText("NISN");

        jLabel5.setText("Jenis Kelamin");

        jkSiswaTxt.add(jkLakiRdo);
        jkLakiRdo.setText("Laki-laki");
        jkLakiRdo.setActionCommand("L");

        jkSiswaTxt.add(jkPerRdo);
        jkPerRdo.setText("Perempuan");
        jkPerRdo.setActionCommand("P");

        jLabel6.setText("Agama");

        jLabel7.setText("Tempat Lahir");

        jLabel8.setText("Tanggal Lahir");

        jLabel9.setText("Alamat");

        agamaSiswaTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Hindu", "Buddha", "Kong Hu Cu" }));

        alamatSiswaTxt.setColumns(20);
        alamatSiswaTxt.setRows(5);
        alamatSiswaTxt.setTabSize(5);
        jScrollPane1.setViewportView(alamatSiswaTxt);

        talaSiswaTxt.setDateFormatString("yyyy-MM-dd"); // NOI18N

        siswaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        siswaTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siswaTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(siswaTbl);

        batalBtn.setText("Batal");
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });

        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        newBtn.setText("New");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Nomor Telepon");

        notelpSiswaTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        nisnSiswaTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(batalBtn)
                        .addGap(249, 249, 249)
                        .addComponent(newBtn)
                        .addGap(18, 18, 18)
                        .addComponent(hapusBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(namaSiswaTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jkLakiRdo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jkPerRdo))
                            .addComponent(agamaSiswaTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kodeSiswaTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nisnSiswaTxt))
                        .addGap(198, 198, 198)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(notelpSiswaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                .addComponent(telaSiswaTxt, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(talaSiswaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(simpanBtn)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kodeSiswaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(telaSiswaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaSiswaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(talaSiswaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(notelpSiswaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nisnSiswaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jkLakiRdo)
                            .addComponent(jkPerRdo))
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(agamaSiswaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batalBtn)
                    .addComponent(simpanBtn)
                    .addComponent(newBtn)
                    .addComponent(hapusBtn)
                    .addComponent(editBtn))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        reset();
        changeInputState(false);
        changeBtnState(false, "batal");
    }//GEN-LAST:event_batalBtnActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        changeInputState(true);
        changeBtnState(true, "new");
    }//GEN-LAST:event_newBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        String kd_siswa = kodeSiswaTxt.getText();
        try (Statement stmt = db.createStatement()) {
            stmt.execute("DELETE FROM `siswa` WHERE `kd_siswa` = '"+kd_siswa+"'");
        } catch (SQLException ex) {
            Logger.getLogger(Siswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
        reset();
        changeInputState(false);
        changeBtnState(false, "simpan");
        siswaTbl.clearSelection();
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        String kd_siswa = kodeSiswaTxt.getText();
        String nm_siswa = namaSiswaTxt.getText();
        String nisn = nisnSiswaTxt.getText();
        String jk = jkSiswaTxt.getSelection().getActionCommand();
        String agama = agamaSiswaTxt.getSelectedItem().toString();
        String tempat = telaSiswaTxt.getText();
        String tanggal = new java.sql.Date(talaSiswaTxt.getDate().getTime()).toString();
        String alamat = alamatSiswaTxt.getText();
        String telp = notelpSiswaTxt.getText();
        
        try (Statement stmt = db.createStatement()) {
            stmt.execute("UPDATE `siswa` SET "
                    + "`nm_siswa` = '"+nm_siswa+"', "
                    + "`nisn` = '"+nisn+"', "
                    + "`kelamin` = '"+jk+"', "
                    + "`agama` = '"+agama+"', "
                    + "`tempat_lahir` = '"+tempat+"', "
                    + "`tanggal_lahir` = '"+tanggal+"', "
                    + "`alamat` = '"+alamat+"', "
                    + "`no_telepon` = '"+telp+"' "
                + "WHERE `kd_siswa` = '"+kd_siswa+"'");
        } catch (SQLException ex) {
            Logger.getLogger(Siswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
        reset();
        changeInputState(false);
        changeBtnState(false, "simpan");
        siswaTbl.clearSelection();
    }//GEN-LAST:event_editBtnActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        try (PreparedStatement ps = db.prepareStatement("INSERT INTO `siswa` VALUES (?,?,?,?,?,?,?,?,?)")) {
            java.sql.Date tanggal = new java.sql.Date(talaSiswaTxt.getDate().getTime());
            ps.setString(1, kodeSiswaTxt.getText());
            ps.setString(2, namaSiswaTxt.getText());
            ps.setString(3, nisnSiswaTxt.getText());
            ps.setString(4, jkSiswaTxt.getSelection().getActionCommand());
            ps.setString(5, agamaSiswaTxt.getSelectedItem().toString());
            ps.setString(6, telaSiswaTxt.getText());
            ps.setString(7, tanggal.toString());
            ps.setString(8, alamatSiswaTxt.getText());
            ps.setString(9, notelpSiswaTxt.getText());
            
            ps.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Siswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
        reset();
        changeInputState(false);
        changeBtnState(false, "simpan");
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void siswaTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siswaTblMouseClicked
        TableModel table = siswaTbl.getModel();
        int row = siswaTbl.getSelectedRow();
        String id = table.getValueAt(row, 0).toString();

        try (PreparedStatement ps = db.prepareStatement("SELECT * FROM `siswa` WHERE `kd_siswa` = ?")) {
            ps.setString(1, id);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                kodeSiswaTxt.setText(rs.getString("kd_siswa"));
                namaSiswaTxt.setText(rs.getString("nm_siswa"));
                nisnSiswaTxt.setText(rs.getString("nisn"));
                if (rs.getString("kelamin").equals("L")) {
                    jkLakiRdo.setSelected(true);
                } else {
                    jkPerRdo.setSelected(true);
                }
                agamaSiswaTxt.setSelectedItem(rs.getString("agama"));
                telaSiswaTxt.setText(rs.getString("tempat_lahir"));
                talaSiswaTxt.setDate(java.sql.Date.valueOf(rs.getString("tanggal_lahir")));
                alamatSiswaTxt.setText(rs.getString("alamat"));
                notelpSiswaTxt.setText(rs.getString("no_telepon"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Siswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        changeInputState(true);
        changeBtnState(true, "edit/delete");
        kodeSiswaTxt.setEnabled(false);
    }//GEN-LAST:event_siswaTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agamaSiswaTxt;
    private javax.swing.JTextArea alamatSiswaTxt;
    private javax.swing.JButton batalBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jkLakiRdo;
    private javax.swing.JRadioButton jkPerRdo;
    private javax.swing.ButtonGroup jkSiswaTxt;
    private javax.swing.JTextField kodeSiswaTxt;
    private javax.swing.JTextField namaSiswaTxt;
    private javax.swing.JButton newBtn;
    private javax.swing.JFormattedTextField nisnSiswaTxt;
    private javax.swing.JFormattedTextField notelpSiswaTxt;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JTable siswaTbl;
    private com.toedter.calendar.JDateChooser talaSiswaTxt;
    private javax.swing.JTextField telaSiswaTxt;
    // End of variables declaration//GEN-END:variables
}
